PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS accounts (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,type TEXT NULL,is_active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,kind TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payees (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL,account_id INTEGER NOT NULL,category_id INTEGER NOT NULL,payee_id INTEGER NULL,amount INTEGER NOT NULL,memo TEXT NULL,status TEXT NOT NULL DEFAULT 'booked',FOREIGN KEY(account_id) REFERENCES accounts(id),FOREIGN KEY(category_id) REFERENCES categories(id),FOREIGN KEY(payee_id) REFERENCES payees(id));
CREATE TABLE IF NOT EXISTS planned_transactions (id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL,account_id INTEGER NOT NULL,amount INTEGER NOT NULL,memo TEXT NULL,status TEXT NOT NULL DEFAULT 'planned',FOREIGN KEY(account_id) REFERENCES accounts(id));
CREATE TABLE IF NOT EXISTS periods (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,budget_amount INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS settings (id INTEGER PRIMARY KEY AUTOINCREMENT,key TEXT UNIQUE NOT NULL,value TEXT NULL);
